version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/configs/:/config/
    command: [
      "java", "-jar", "app.jar",
      "--spring.config.additional-location=optional:file:/config/"
    ]