spring:
  application:
    name: modi

  config:
    import: optional:file:/config/application-secret.yml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

app:
  frontend:
    local: https://localhost:5173
    prod: https://modi-frontend-nu.vercel.app
  mode: prod # local 또는 prod, 배포 시 변경 가능

openai:
  api:
    key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET}
