spring:
  application:
    name: modi

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:modidb.xxxxxx.ap-northeast-2.rds.amazonaws.com}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
