spring:
  application:
    name: modi

  config:
    import: optional:classpath:application-secret.yml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/modidb?serverTimezone=Asia/Seoul
    username: root
    password: cjstk10452!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}