spring:
  application:
    name: modi

  config:
    import: optional:file:/config/application-secret.yml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

server:
  port: 8080