package kuit.modi.controller;

import com.fasterxml.jackson.core.JsonProcessingException;
import kuit.modi.dto.ai.request.AutoGenerateRequest;
import kuit.modi.dto.ai.request.LanguageStyleRequest;
import kuit.modi.dto.ai.request.StyledSummaryRequest;
import kuit.modi.dto.ai.request.SummaryRequest;
import kuit.modi.dto.ai.response.AutoGenerateResponse;
import kuit.modi.dto.ai.response.LanguageStyleResponse;
import kuit.modi.dto.ai.response.SummaryResponse;
import kuit.modi.service.AiUtilsService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/utils")
@RequiredArgsConstructor
public class AiUtilsController {
    private final AiUtilsService aiUtilsService;

    @PostMapping("/auto-generate")
    public ResponseEntity<AutoGenerateResponse> autoGenerate(@RequestBody AutoGenerateRequest request) {
        String result = aiUtilsService.autoGenerateDiary(request);
        return ResponseEntity.ok(new AutoGenerateResponse(result));
    }

    @PostMapping("/summary")
    public ResponseEntity<SummaryResponse> summarize(@RequestBody SummaryRequest request) {
        String summary = aiUtilsService.summarizeDiary(request);
        return ResponseEntity.ok(new SummaryResponse(summary));
    }

    @PostMapping("/language-style")
    public ResponseEntity<LanguageStyleResponse> languageStyle(@RequestBody LanguageStyleRequest request) throws JsonProcessingException {
        LanguageStyleResponse response = aiUtilsService.extractLanguageStyle(request);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/summary/styled")
    public ResponseEntity<SummaryResponse> summaryStyled(@RequestBody StyledSummaryRequest request) {
        String summary = aiUtilsService.getStyledSummary(request);
        return ResponseEntity.ok(new SummaryResponse(summary));
    }
}
