package kuit.modi.service;

import kuit.modi.dto.ai.AutoGenerateRequest;
import kuit.modi.dto.ai.LanguageStyleRequest;
import kuit.modi.dto.ai.SummaryRequest;
import kuit.modi.openai.OpenAiClient;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AiUtilsService {
    private final OpenAiClient openAiClient;

    public String autoGenerateDiary(AutoGenerateRequest request) {
        // 예: 프롬프트 생성
        String prompt = "다음 태그들을 바탕으로 일기를 작성해줘: " + String.join(", ", request.getTags());
        return openAiClient.ask(prompt);
    }

    public String summarizeDiary(SummaryRequest request) {
        String prompt = "다음 일기를 40자 이내로 요약해줘:\n" + request.getContent();
        return openAiClient.ask(prompt);
    }

    public List<String> extractLanguageStyle(LanguageStyleRequest request) {
        String prompt = "다음 일기에 어울리는 감정 스타일을 3~4개 뽑아줘:\n" + request.getContent();
        String response = openAiClient.ask(prompt);
        return Arrays.stream(response.split("[,\\n]"))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toList());
    }
}
