package kuit.modi.service;

import kuit.modi.dto.ai.request.AutoGenerateRequest;
import kuit.modi.dto.ai.request.LanguageStyleRequest;
import kuit.modi.dto.ai.request.StyledSummaryRequest;
import kuit.modi.dto.ai.request.SummaryRequest;
import kuit.modi.openai.OpenAiClient;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AiUtilsService {
    private final OpenAiClient openAiClient;

    private static final String SYSTEM_ROLE_AUTO_GENERATE =
            "당신은 사용자의 태그를 기반으로 감성적인 일기를 짧게 작성하는 전문가입니다.";
    private static final String SYSTEM_ROLE_SUMMARY =
            "당신은 사용자의 일기를 간결하고 핵심적으로 요약하는 전문가입니다.";
    private static final String SYSTEM_ROLE_LANGUAGE_STYLE =
            "당신은 AI 일기 생성 및 요약 서비스에 사용될 도우미입니다. 주어진 일기와 사용자가 선택한 감정을 기반으로 몇 가지 적절한 언어 스타일을 제시합니다. 언어 스타일은 '기쁨', '슬픔', '화남' 등과 같이 명사형으로 제공되며 이 서비스에서는 선택된 언어 스타일을 적용하여 해당 감정이 드러나도록 일기를 다시 쓰는 기능도 제공합니다.";
    private static final String SYSTEM_ROLE_STYLED_SUMMARY =
            "당신은 주어진 요약에 특정 언어 스타일을 적용해 재작성하는 전문가입니다.";

    public String autoGenerateDiary(AutoGenerateRequest request) {
        String userPrompt = "제시된 태그들을 바탕으로 띄어쓰기 포함 200자 이내의 일기를 생성해줘. 태그들은 다음과 같아: "
                + String.join(", ", request.getTags());
        return openAiClient.ask(SYSTEM_ROLE_AUTO_GENERATE, userPrompt);
    }

    public String summarizeDiary(SummaryRequest request) {
        String userPrompt = "다음 일기를 띄어쓰기 포함 40자 이내로 요약해줘:\n" + request.getContent();
        return openAiClient.ask(SYSTEM_ROLE_SUMMARY, userPrompt);
    }

    public List<String> extractLanguageStyle(LanguageStyleRequest request) {
        String userPrompt = "\"" + request.getEmotion()
                + "\"(이)라는 감정에서 크게 벗어나지 않도록 다음 일기에 어울리는 언어 스타일을 3~4개 뽑아줘. 일기 내용:\n"
                + request.getSummary();
        String response = openAiClient.ask(SYSTEM_ROLE_LANGUAGE_STYLE, userPrompt);

        return Arrays.stream(response.split("\\r?\\n"))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .map(s -> s.replaceFirst("^(\\d+\\.|-)+\\s*", ""))
                .collect(Collectors.toList());
    }

    public String getStyledSummary(StyledSummaryRequest request) {
        String userPrompt = "\"" + request.getStyle()
                + "\"이라는 언어 스타일을 적용해서 다음의 일기 요약을 띄어쓰기 포함 40자 이내로 다시 써줘: \n"
                + request.getSummary();
        return openAiClient.ask(SYSTEM_ROLE_STYLED_SUMMARY, userPrompt);
    }
}

