name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 SSH 접속 후 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 20m
          command_timeout: 20m
          script: |
            cd ~/MODI-backend
            docker-compose down
            docker rmi -f $(docker images "modi-backend-app" -q)
            git pull origin main
            ./gradlew clean build -x test
            docker-compose up --build -d