name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 SSH 접속 후 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 20m
          command_timeout: 20m
          script: |
            set -e

            cd ~/MODI-backend

            echo "==> Git 동기화 (강제)"
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            echo "==> 기존 컨테이너/이미지 정리"
            docker-compose down || true
            docker images -f "dangling=true" -q | xargs -r docker rmi -f
            docker images "modi-backend-app" -q | xargs -r docker rmi -f

            echo "==> Gradle 실행권한 부여"
            chmod +x ./gradlew

            echo "==> Gradle 클린 빌드 (테스트 생략)"
            ./gradlew clean bootJar -x test --refresh-dependencies

            echo "==> 도커 캐시 없이 재빌드/재기동"
            docker-compose build --no-cache
            docker-compose up -d --force-recreate

            echo "==> 빌드 산출물/이미지에 v1 흔적 없는지 검사"
            grep -R "import com.amazonaws" -n src/main/java || true
            grep -a "AmazonS3" build/libs/*.jar || true